site_name: Imputation Server 2
repo_name: bystrogenomics/imputationserver2
repo_url: https://github.com/bystrogenomics/imputationserver2
edit_uri: edit/master/docs

theme:
  name: material
  features:
    - content.tooltips
    #- navigation.expand
    - navigation.tabs
    #- navigation.tabs.sticky
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    #- toc.integrate
    - content.tabs.link
    - content.code.annotate
    - content.code.copy
  font:
    text: Segoe UI #Avenir
    code: Roboto Mono

  palette:
    primary: custom
    accent: blue
  favicon: images/favicon.svg

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Contact: contact.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - attr_list
  - md_in_html
  - toc:
      title: On this page
      permalink: true
